### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ArtVandelayCS** [xaitax/PatchaPalooza#1]
Getting an error when trying to run:

/PatchaPalooza$ python PatchaPalooza.py
  File "PatchaPalooza.py", line 17
    endpoint = f"{BASE_URL}updates"
                                  ^
SyntaxError: invalid syntax

python3 is already the newest version (3.8.2-0ubuntu2).

**Comment by xaitax** [comment]
Are you sure that you are running the script with `python3` and not python2? `python` might still refer to python2 maybe? Since f-strings where introduced in python3.6.

**Comment by ArtVandelayCS** [comment]
I was running python2 not 3... thank you very much!
