### ISSUE TITLE
patchapalooza.com doesn't work

### ISSUE THREAD

**Issue by eric-therond** [xaitax/PatchaPalooza#2]
thanks for this project

I suppose you are aware of patchapalooza.com which is making requests to a not reachable backend and thus data cannot be fetched:

![image](https://github.com/xaitax/PatchaPalooza/assets/11455652/dff53643-5226-41ab-83a4-1cd3d41f6dd8)

is that possible to make open-source the frontend / backend of patchapalooza.com ?

**Comment by xaitax** [comment]
Thank you @eric-therond - I fixes the issue and it should work again. 

Maybe I will open source the whole tool one day but for the moment the code is quite messy and a lot of unneccassry parts in it. Will need time to refactor and then I might release it.

Thanks again for letting me know about the issue!
